### PR TITLE
Improve dockerfile and add nodemon

### PR DESCRIPTION
**Pull request by James-Quigley**
Adds nodemon (auto restart app on file change) for local development and adds some Node/Docker best practices

### CODE REVIEW

**Comment by azlyth** [comment]
What functionality does `NODE_ENV` toggle here?

**Comment by James-Quigley** [comment]
> What functionality does `NODE_ENV` toggle here?

Technically nothing. But its commonly used by packages as a basis of whether or not to run in dev mode. could be removed since we aren't really using it.

**Comment by azlyth** [comment]
We can leave `NODE_ENV`, was just making sure I wasn't missing something.

Otherwise looks good, I'll merge later after I make a slight adjustment to the volume setup.

**Comment by ktomanelli** [comment]
Had to revert this change as it prevented app from starting

**Pull request merged**
